# Generated by Django 6.0.4 on 2026-05-17 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('trainer_salary', 'Trainer Salary'), ('equipment', 'Equipment'), ('utilities', 'Utilities'), ('maintenance', 'Maintenance'), ('marketing', 'Marketing'), ('supplies', 'Supplies'), ('rent', 'Rent'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.gym')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-date'],
            },
        ),
    ]
