# Generated by Django 6.0.4 on 2026-05-17 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='trainers.trainer'),
        ),
        migrations.AddField(
            model_name='package',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='accounts.gym'),
        ),
        migrations.AddField(
            model_name='client',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='clients.package'),
        ),
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.client'),
        ),
        migrations.AddField(
            model_name='payment',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.gym'),
        ),
    ]
